server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  resolver 127.0.0.11 ipv6=off;

  location / { try_files $uri $uri/ /index.html; }
  location /api/ {
    set $api_upstream http://api:4000;
    proxy_pass $api_upstream;
  }
  location /auth/ {
    set $api_upstream http://api:4000;
    proxy_pass $api_upstream;
  }
  location /health {
    set $api_upstream http://api:4000;
    proxy_pass $api_upstream;
  }
}
