server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  resolver 8.8.8.8 ipv6=off;

  location / { try_files $uri $uri/ /index.html; }
  location /api/ {
    set $api_upstream https://scamsafeapi-production.up.railway.app;
    proxy_pass $api_upstream;
    proxy_set_header Host scamsafeapi-production.up.railway.app;
    proxy_ssl_server_name on;
  }
  location /auth/ {
    set $api_upstream https://scamsafeapi-production.up.railway.app;
    proxy_pass $api_upstream;
    proxy_set_header Host scamsafeapi-production.up.railway.app;
    proxy_ssl_server_name on;
  }
  location /health {
    set $api_upstream https://scamsafeapi-production.up.railway.app;
    proxy_pass $api_upstream;
    proxy_set_header Host scamsafeapi-production.up.railway.app;
    proxy_ssl_server_name on;
  }
}
